@echo off
echo Creating SecurePath UK Google Drive Folders...
C:\SecurePathUK\tools\gdrive.exe mkdir "01_Clients"
C:\SecurePathUK\tools\gdrive.exe mkdir "Active_Clients" -p "01_Clients"
C:\SecurePathUK\tools\gdrive.exe mkdir "Prospects" -p "01_Clients"
C:\SecurePathUK\tools\gdrive.exe mkdir "Completed_Projects" -p "01_Clients"
C:\SecurePathUK\tools\gdrive.exe mkdir "Templates" -p "01_Clients"
C:\SecurePathUK\tools\gdrive.exe mkdir "02_Operations"
C:\SecurePathUK\tools\gdrive.exe mkdir "Policies_Procedures" -p "02_Operations"
C:\SecurePathUK\tools\gdrive.exe mkdir "Security_Documentation" -p "02_Operations"
C:\SecurePathUK\tools\gdrive.exe mkdir "ISO_27001_Framework" -p "02_Operations"
C:\SecurePathUK\tools\gdrive.exe mkdir "Compliance_Evidence" -p "02_Operations"
C:\SecurePathUK\tools\gdrive.exe mkdir "03_Finance"
C:\SecurePathUK\tools\gdrive.exe mkdir "Invoices" -p "03_Finance"
C:\SecurePathUK\tools\gdrive.exe mkdir "Contracts" -p "03_Finance"
C:\SecurePathUK\tools\gdrive.exe mkdir "Financial_Reports" -p "03_Finance"
C:\SecurePathUK\tools\gdrive.exe mkdir "Budgets" -p "03_Finance"
C:\SecurePathUK\tools\gdrive.exe mkdir "04_Marketing"
C:\SecurePathUK\tools\gdrive.exe mkdir "Content" -p "04_Marketing"
C:\SecurePathUK\tools\gdrive.exe mkdir "Campaigns" -p "04_Marketing"
C:\SecurePathUK\tools\gdrive.exe mkdir "Brand_Assets" -p "04_Marketing"
C:\SecurePathUK\tools\gdrive.exe mkdir "Case_Studies" -p "04_Marketing"
C:\SecurePathUK\tools\gdrive.exe mkdir "05_Internal"
C:\SecurePathUK\tools\gdrive.exe mkdir "Team_Resources" -p "05_Internal"
C:\SecurePathUK\tools\gdrive.exe mkdir "Training_Materials" -p "05_Internal"
C:\SecurePathUK\tools\gdrive.exe mkdir "Meeting_Notes" -p "05_Internal"
C:\SecurePathUK\tools\gdrive.exe mkdir "Project_Management" -p "05_Internal"
C:\SecurePathUK\tools\gdrive.exe mkdir "06_Technical"
C:\SecurePathUK\tools\gdrive.exe mkdir "Architecture_Docs" -p "06_Technical"
C:\SecurePathUK\tools\gdrive.exe mkdir "API_Documentation" -p "06_Technical"
C:\SecurePathUK\tools\gdrive.exe mkdir "Security_Configs" -p "06_Technical"
C:\SecurePathUK\tools\gdrive.exe mkdir "Automation_Scripts" -p "06_Technical"
echo.
echo ? All folders created!
pause
